more options for encrypt/decrypt

diff --git a/ubuntu/decryptWithGPG2 b/ubuntu/decryptWithGPG2
--- a/ubuntu/decryptWithGPG2
+++ b/ubuntu/decryptWithGPG2
@@ -3,10 +3,50 @@
 # This script will reverse the effects of the
 # encryptWithGPG2.sh script: use gpg2 to decrypt the file and send it to stdout
 # (in this case the pipeline), then extract the tar file contents into the
-# current directory
+# current directory, or in the directory 
 
-if [ -f "$1" ]; then
-  gpg2 -d $1 | tar xzf -
+
+# did you pass an argument?
+if [ ! -z "$1" ]; then
+
+  # do you want to delete the original?
+  destroy_original=false
+  if [ "$1" == '--destroy-original' ]; then
+    echo "original file will be destroyed"
+    destroy_original=true 
+    shift
+  fi
+
+  # did you provide a valid file?
+  if [ -f "$1" ]; then
+
+    # did you provide a destination?
+    if [ ! -z "$2" ]; then
+      echo "argument 2 exists: $2"
+
+      # is the destination a directory?
+      if [ -d "$2" ]; then
+        echo "got to the tar -C: $2"
+        gpg2 -d $1 | tar xzf - -C $2
+      else
+        echo "$2 needs to be a directory you can write to." 1>&2
+      fi
+
+    else
+      echo "could not detect argument 2: $2"
+      gpg2 -d $1 | tar xzf -
+    fi
+
+    # did you actually want to destroy the original?
+    if [ "$destroy_original" == true ]; then
+      echo 'destroying original...'
+      rm -f $1
+    fi
+
+  else
+    echo "file $1 not found" 1>&2
+  fi
+
 else
-  echo "file $1 not found" 1>&2
+  echo "you must provide an encrypted tarball as argument" 1>&2
 fi
diff --git a/ubuntu/encryptWithGPG2 b/ubuntu/encryptWithGPG2
--- a/ubuntu/encryptWithGPG2
+++ b/ubuntu/encryptWithGPG2
@@ -2,8 +2,59 @@
 
 # This script will turn a file or directory into a tar ball, send it down the
 # pipe to gpg2, which will then ask you for a passphrase for it and encrypt it
-if [ -e $1 ]; then
-  tar czf - $1 | gpg2 -c --output "$1.gpg" - 
+
+# did you pass an argument?
+if [ ! -z "$1" ]; then
+  echo "$1"
+
+  # do you want to delete the original?
+  destroy_original=false
+  if [ "$1" == '--destroy-original' ]; then
+    echo "original file will be destroyed"
+    destroy_original=true 
+    shift
+  fi
+
+
+  # did you provide a valid argument?
+  if [ -e $1 ]; then
+
+    # did you provide a destination?
+    if [ ! -z "$2" ]; then
+      #echo "argument 2 exists: $2"
+
+      # is the destination a directory?
+      if [ -d "$2" ]; then
+        # does your directory name end with a '/'
+        dir=$2
+        dirlength=${#dir}
+        if [ ${dir:-1} == '/' ]; then
+          dir=${dir:0:$dirlength-1}
+        fi
+
+        #echo "got to the tar -C: $2"
+        echo "saving encrypted file at $2/$1"
+        tar czf - $1 | gpg2 -c --output "$2/$1.gpg" - 
+
+      else
+        echo "$2 needs to be a directory you can write to." 1>&2
+      fi
+    else
+      #echo "could not detect argument 2: $2"
+      echo "saving in current directory"
+      tar czf - $1 | gpg2 -c --output "$1.gpg" - 
+    fi
+
+  else
+    echo "You must specify a valid file or directory as your argument" 1>&2
+  fi
+
+  # did you actually want to destroy the original?
+  if [ "$destroy_original" == true ]; then
+    echo 'destoying original...'
+    rm -rf $1
+  fi
+
 else
-  echo "You must specify a valid directory as your argument" 1>&2
+  echo "you must provide a file or directory as an argument" 1>&2
 fi
